name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  UPLOAD_DIR: upload

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              build_type: release
            - os: windows-latest
              build_type: release
            - os: macos-latest
              build_type: release
            - os: ubuntu-latest
              build_type: debug
            - os: windows-latest
              build_type: debug
            - os: macos-latest
              build_type: debug

    steps:
    - name: Checkout code (All)
      uses: actions/checkout@v4

    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install wget zip

    - name: Build
      shell: bash
      run: |
        ./build.sh ${{ matrix.build_type }}

    - name: Bundle
      shell: bash
      run: |
        zip -r build.zip build/
        mkdir -p "${{ env.UPLOAD_DIR }}"
        mv build.zip "${{ env.UPLOAD_DIR }}"

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}
        path: ${{ env.UPLOAD_DIR }}
